@startuml

package presentation {
   	package Controller as p_ctl {

   	}
   	package Aspect as p_asp {

   	}
   	package Session as p_ssn {

   	}
   	package View as p_vw {

   	}
   	package Form as p_fm {

   	}
   	package Converter as p_cvtr {

   	}
}

package domain {
	package ValueObject as d_vo {

   	}

   	package Service as d_svc {

   	}

   	package Repository as d_rp {

    }

    package Model as d_mdl {

    }

}

package infrastructure {
   	package InMemory as i_im {

   	}
	package PostgreSQL as i_pgsql {

   	}
	package Entity as i_ety {

   	}
   	package Converter as i_cvtr {

   	}
}

package usecase {
    package Service as u_svc {

    }
}


/' プレゼンテーション層の依存関係 '/
i_cvtr ---> d_mdl
i_cvtr -> i_ety
i_im ...> d_rp
i_pgsql ..> d_rp

p_vw --> p_ctl
p_vw --> p_fm
p_ctl --> p_fm
p_ctl --> p_cvtr
p_cvtr -> p_fm
p_cvtr ---> d_mdl
p_ctl --> u_svc

u_svc --> d_rp
u_svc --> d_svc
d_svc --> d_rp
d_mdl -> d_vo



@enduml