@startuml Yabom TRIP Domain

package イベント {
    object イベント {
        イベント名
        内容
        予定開始日時
        予定終了日時
        イベント場所
    }
    object イベント参加者 {
    	イベント
    	参加者
    }
}

package TODOリスト集約 {
    object TODO {
        タイトル
        内容
        チェックリスト
        予定開始日時
        リマインド設定
    }
    object チェックリスト{
        内容
        状態
    }
}

package ユーザー集約 {
    object ユーザー{
        名前
        写真
        メールアドレス
        電話番号
    }
    object 認証情報 {
        ユーザーID
        パスワード
    }
}

package スケジュール集約 {
    object スケジュール {
        タイトル
        予定開始日時
        予定終了日時
        詳細情報
    }
}

package 共有情報集約 {
    object 共有情報 {
        タイトル
        詳細情報
        写真
    }
    object アルバム {
    }
    object 交通情報 {
    }
    object 見どころ情報 {
    }
    object コメント {
        ユーザーID
        コメント内容
    }
}




/' 親要素を左に書くようにする '/
/' → 左側は必ずないといけないもの '/
/' → 右側は必須ではない '/
/' 集約間の関係 '/
イベント "1" ---> "1..n" ユーザー集約
イベント "1" <-- "0..n" TODO
イベント "1" <-- "0..n" スケジュール
イベント "1" <-- "0..n" 共有情報
TODO "1" ---> "1" ユーザー集約
スケジュール "1" ---> "1" ユーザー集約
コメント "1" ---> "1" ユーザー集約

/' 各集約内の関係 '/
イベント "1" *-- "1..n" イベント参加者
TODO "1" *-- "0..n" チェックリスト
共有情報 "1" *-- "0..n" アルバム
共有情報 "1" *-- "0..n" 交通情報
共有情報 "1" *-- "0..n" 見どころ情報
共有情報 "1" *-- "0..n" コメント
ユーザー "1" *-- "1" 認証情報





/' 吹き出し '/
note top of TODO
■タイトル
*必須項目 / 全角100文字まで
end note

note bottom of チェックリスト
■内容
*必須項目 / 全角400文字まで
■状態
*未完了 or 完了の２種類
*初期状態は未完了
end note

note bottom of 認証情報
■パスワード
*半角8文字以上
*記号を含ませること
end note



@enduml