@startuml

package イベント {
    object イベント {
        イベント名
        内容
        参加者
        予定開始日時
        予定終了日時
        イベント場所
    }
}

package TODOリスト集約 {
    object TODO {
        タイトル
        内容
        チェックリスト
        予定開始日時
        リマインド設定
    }
    object チェックリスト{
        内容
        状態
    }
}

package ユーザー集約 {
    object ユーザー{
        名前
        写真
        メールアドレス
        電話番号
    }
    object 認証情報 {
        ユーザーID
        パスワード
    }
}

package アルバム集約 {
    object アルバム {
        タイトル
        写真
        コメント
    }
    object コメント {
        ユーザーID
        コメント内容
    }
}

package プラン集約 {
    object プラン {
        タイトル
        予定開始日時
        予定終了日時
        詳細情報
    }
}

package 共有情報集約 {
    object 共有情報 {
        タイトル
        詳細情報
    }
}

/' 親要素を左に書くようにする '/
/' → 左側は必ずないといけないもの '/
/' → 右側は必須ではない '/
イベント "1" ---> "1..n" ユーザー:ユーザーIDを参照する
イベント "1" *-- "0..n" TODO:TODOはイベント内に含まれる
イベント "1" *-- "0..n" アルバム:アルバムはイベント内に含まれる
イベント "1" *-- "0..n" プラン:プランはイベント内に含まれる
イベント "1" *-- "0..n" 共有情報:共有情報はイベント内に含まれる
TODO "1" *-- "0..n" チェックリスト
TODO "1" ---> "1" ユーザー

アルバム "1" *-- "0..n" コメント
アルバム "1" ---> "1" ユーザー

プラン "1" ---> "1" ユーザー

ユーザー "1" *-- "1" 認証情報

/' 吹き出し '/
note left of TODO
■タイトル
*必須項目 / 全角100文字まで
end note

note bottom of チェックリスト
■内容
*必須項目 / 全角400文字まで
■状態
*未完了 or 完了の２種類
*初期状態は未完了
end note

note bottom of 認証情報
■パスワード
*半角8文字以上
*記号を含ませること
end note



@enduml