@startuml

actor ユーザー
left to right direction
rectangle イベント {
    
    ユーザー -- (イベントに参加する)

    package TODOリスト {
        ユーザー -- (TODOリストを追加する)
        ユーザー -- (チェックリストを完了する)
    }
    package アルバム {
        ユーザー -- (アルバムを見る)
        ユーザー -- (アルバムを追加する)
        ユーザー -- (アルバムにコメントする)
    }
    package スケジュール {
        ユーザー -- (スケジュールを確認する)
        ユーザー -- (スケジュールを追加する)
        ユーザー -- (スケジュールを編集する)
    }
    package 見どころ {
        ユーザー -- (見どころを確認する)
        ユーザー -- (見どころをアップロードする)
        ユーザー -- (見どころを編集する)
    }
    package 交通情報 {
        ユーザー -- (交通情報を検索する)
        ユーザー -- (交通情報を確認する)
        ユーザー -- (交通情報をお気に入りする)
        ユーザー -- (交通情報の通知設定をする)
    }
}

@enduml