@startuml

actor ユーザー
left to right direction
rectangle イベント {
    
    ユーザー -- (イベントに参加する)

    package TODOリスト {
        ユーザー -- (TODOリストを追加する)
        ユーザー -- (チェックリストを完了する)
    }
    package アルバム {
        ユーザー -- (アルバムを見る)
        ユーザー -- (アルバムを追加する)
        ユーザー -- (アルバムにコメントする)
    }
    package プラン {
        ユーザー -- (プランを確認する)
        ユーザー -- (プランを追加する)
        ユーザー -- (プランを編集する)
    }
    package 情報共有 {
        ユーザー -- (情報を確認する)
        ユーザー -- (情報をアップロードする)
        ユーザー -- (情報を編集する)
    }
}

@enduml